// Copyright (c) FIRST and other WPILib contributors.
// Open Source Software; you can modify and/or share it under the terms of
// the WPILib BSD license file in the root directory of this project.

package frc.robot.data;

import com.ctre.phoenix6.CANBus;

/**
 * Every CAN device on the robot, paired with the bus it lives on.
 *
 * <p>
 * CAN IDs are only unique per bus, so an ID on its own does not identify a
 * device. Keeping the two together makes it impossible to construct a device
 * without saying which bus it is on — the mistake that produces a silently
 * unresponsive motor.
 *
 * <p>
 * Drivetrain devices are not listed here. They live in {@link TunerConstants},
 * which is generated by CTRE Tuner X and would lose hand edits on regeneration.
 * They occupy IDs 1-12 on the CANivore.
 */
public enum Ports {
  /* RIO bus */
  EXPANDER_MOTOR(14, Bus.RIO),
  INTAKE_MOTOR_1(15, Bus.RIO),
  INTAKE_MOTOR_0(16, Bus.RIO),
  CLIMBER_MOTOR(17, Bus.RIO),
  INDEXER_MOTOR_1(18, Bus.RIO),
  INDEXER_MOTOR_2(19, Bus.RIO),
  FEEDER_MOTOR_0(20, Bus.RIO),
  FLYWHEEL_MOTOR_0(21, Bus.RIO),
  FLYWHEEL_MOTOR_1(22, Bus.RIO),
  HOOD_MOTOR(23, Bus.RIO),
  CANDLE(24, Bus.RIO),
  FEEDER_MOTOR_1(28, Bus.RIO),

  /* CANivore bus */
  TURRET_MOTOR(25, Bus.CANIVORE),
  TURRET_ENCODER_0(26, Bus.CANIVORE), // 35t
  TURRET_ENCODER_1(27, Bus.CANIVORE); // 36t

  public final int id;
  public final CANBus bus;

  Ports(int id, CANBus bus) {
    this.id = id;
    this.bus = bus;
  }

  /**
   * The robot's CAN buses. Nested so that the enum constants above can reference
   * them in their constructor arguments.
   */
  public static final class Bus {
    public static final CANBus RIO = new CANBus("rio");
    public static final CANBus CANIVORE = new CANBus("CANivore");

    private Bus() {}
  }

  /**
   * Returns the first pair of ports sharing an ID on the same bus, or null if
   * there are none. Drivetrain IDs are not covered — see the class comment.
   */
  public static String findDuplicate() {
    for (Ports a : values()) {
      for (Ports b : values()) {
        if (a.ordinal() < b.ordinal() && a.id == b.id && a.bus.getName().equals(b.bus.getName())) {
          return a + " and " + b + " share ID " + a.id + " on " + a.bus.getName();
        }
      }
    }
    return null;
  }
}
